openapi: 3.0.2
info:
  title: eStudentBookAPI
  description: empty
  version: 1.0.0

tags:
  - name: 'user-query'
  - name: 'subject-command'
  - name: 'students-query'
  - name: 'students-command'

paths:
  /users/new:
    $ref: paths/users/users.yaml

  /students/groups:
    $ref: paths/users/students/students-in-groups.yaml
  /students/{student-uuid}:
    $ref: paths/users/students/student.yaml
  /students/{student-uuid}/subject-cards/{semester-number}:
    $ref: paths/users/students/subject-card/subject-card.yaml
#  /students/{student-uuid}/subject-cards/{subject-card-uuid}:
#    $ref: paths/users/students/subject-card/
  /students/{student-uuid}/subject-cards/{subject-card-uuid}/grades/{grade-uuid}:
    $ref: paths/users/students/subject-card/grade.yaml
#  /students/{student-uuid}/subject-cards/{subject-card-uuid}/grades/new:
#    $ref: paths/users/students/subject-card/

#  /professor/{professor-uuid}/subjects/:
#    $ref:
#  /professor/{professor-uuid}/subjects/{subject-uuid}:
#    $ref:

  /subjects:
    $ref: paths/subjects/subjects.yaml
  /subjects/{subject-uuid}/:
    $ref: paths/subjects/subject.yaml