openapi: 3.0.2
info:
  title: Title
  description: Title
  version: 1.0.0

tags:
  - name: 'user-query'
  - name: 'subject-command'
  - name: 'students-query'
  - name: 'students-command'

paths:
  /users/new:
    $ref: paths/users/users.yaml

  /students/groups:
    $ref: paths/users/students/students-in-groups.yaml
  /students/{student-uuid}/grades/{grade-uuid}:
    $ref: paths/users/students/grade.yaml
  /students/{student-uuid}/grades:
    $ref: paths/users/students/grades.yaml
  /students/{student-uuid}:
    $ref: paths/users/students/student.yaml

  /subjects:
    $ref: paths/subjects/subjects.yaml
  /subjects/{subject-uuid}/:
    $ref: paths/subjects/subject.yaml


  
