openapi: 3.0.2
info:
  title: eStudentBookAPI
  description: eStudentBookAPI provides - student, professor and administrator endpoints with authentication
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server address

tags:
  - name: 'user-query'
  - name: 'user-command'
  - name: 'subject-command'
  - name: 'students-query'
  - name: 'students-command'
  - name: 'professors-query'

paths:
  /users:
    $ref: paths/users/user-create.yaml
  /users/auth:
    $ref: paths/users/user-authorize.yaml
  /users/new:
    $ref: paths/users/users.yaml

  /users/students/groups:
    $ref: paths/users/students/students-in-groups.yaml
  /users/students/details:
    $ref: paths/users/students/student.yaml
  /users/students/subject-cards/semesters/{semester-number}:
    $ref: paths/users/students/subject-card/subject-card-by-semester.yaml
  /users/students/subject-cards/subjects/{subject-uuid}:
    $ref: paths/users/students/subject-card/subject-card.yaml
  /users/students/{student-uuid}/subject-cards/{subject-card-uuid}/grades/{grade-uuid}:
    $ref: paths/users/students/subject-card/grade.yaml
  /users/students/{student-uuid}/subject-cards/{subject-card-uuid}/grades:
    $ref: paths/users/students/subject-card/grades.yaml

  /users/professors/details:
    $ref: paths/users/professors/professor.yaml

  /subjects:
    $ref: paths/subjects/subjects.yaml
  /subjects/{subject-uuid}:
    $ref: paths/subjects/subject.yaml