openapi: 3.0.2
info:
  title: Title
  description: Title
  version: 1.0.0

tags:
  - name: 'user-query'
  - name: 'subject-command'

paths:
  /users/new:
    $ref: paths/users/users.yaml

  /subjects:
    $ref: paths/subjects/subjects.yaml
  /subjects/subject-uuid/:
    $ref: paths/subjects/subject.yaml


  
